### ISSUE TITLE
Implement Topic Endpoints

### ISSUE THREAD

**Issue by Nathan-Somto** [hslcreators/lecturedeck-be#11]
Here are the topic endpoints
**Note:** the endpoints are on the group chat (backend topics)

Name your branch as follows:

```git
  git checkout -b your username/feat/topics
```

**Note**
1. Dont open a PR to main
2. Use conventional commits
3. Include test cases

**Comment by Temiloluwa-Ogundiran** [comment]
I would do like to do this!

**Comment by Nathan-Somto** [comment]
Okay no problem in your PR please reference this issue
