### ISSUE TITLE
Auth middleware not getting tokens properly

### ISSUE THREAD

**Issue by Temiloluwa-Ogundiran** [hslcreators/lecturedeck-be#14]
The auth middleware uses "X-AUTH-TOKEN" property on req headers to get token but req header keys are received in all lower case so couldnt retrieve token, request headers are typically like this

### Sample Request Header gotten from Postman
```
{
  'x-auth-token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGEyMDZjMS1kOGU5LTRhN2ItODY1My1mZTE2NWM2YjRkMjMiLCJpYXQiOjE3MDIyNDk5NTcsImV4cCI6MTcwMjY4MTk1N30.hGDEANeFU-j3Nd01mXqegK2dVZ7z7fPnDRchUa9p3jQ',
  'content-type': 'application/json',
  'user-agent': 'PostmanRuntime/7.35.0',
  accept: '*/*',
  'postman-token': '8e9ee336-837c-4cfa-bd56-409719cdbb93',
  host: 'localhost:8000',
  'accept-encoding': 'gzip, deflate, br',
  connection: 'keep-alive',
  'content-length': '100'
}
```

Also the token failed to be retrieved from the x-auth-token property, this line of code tried to get the exact value of token
```
    const token = headers?.split(' ')[1]
```
but has seen in sample above the token is just a single string with no spaces so this line refused to work

considering all of the above I decided to edit the auth middleware (I really did not want to, but to clarify my doubt )
I change this lines of code
```
type AuthHeaders = Headers & {
  'X-Auth-Token': string
}
const auth = async (
  req: Request,
  _res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const headers = (req.headers as AuthHeaders)['X-Auth-Token']
    const token = headers?.split(' ')[1]
```
to
```
type AuthHeaders = Headers & {
  'x-auth-token': string
}
const auth = async (
  req: Request,
  _res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const headers = (req.headers as AuthHeaders)['x-auth-token']
    const token = headers?.split(' ')[0]
```
and the token was properly gotten, user was retrieved and normal flow of route continued
so I dont know if the original would still work in some way, you probably had your reasons for writing it like that maybe there is a different way that I am suppose to send the request

## Lastly in the endpoint pdf you sent, It is stated that authorization would be done using bearer token but code implementation uses X-AUTH-TOKEN, just drawing your attention to it

**Comment by Nathan-Somto** [comment]
that is the intended way to get the token with the index of 1
```js 
const token = headers?.split(' ')[1]
// should be in this form when passed  "Bearer Token"
// e.g
  {
  'x-auth-token': 
'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3MGEyMDZjMS1kOGU5LTRhN2ItODY1My1mZTE2NWM2YjRkMjMiLCJpYXQiOjE3MDIyNDk5NTcsImV4cCI6MTcwMjY4MTk1N30.hGDEANeFU-j3Nd01mXqegK2dVZ7z7fPnDRchUa9p3jQ',
}

```
the  ```x-``` in the ```x-auth-token``` denotes a custom header in the request object.
the only issue I can see is that the property ```x-auth-token``` is in uppercase which is a mistake,
I will implement a fix now.
