### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" when starting server

### ISSUE THREAD

**Issue by Temiloluwa-Ogundiran** [hslcreators/lecturedeck-be#7]
Typescript ES6 error
Server not running on local machine until i change these files

nodemon.json
```
"exec": "ts-node --files --esm"
```
to 
```
"exec": "ts-node"
```

and 

removed this portion of code from tsconfig
```
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  },
````

that portion of code should even be there in the first place because this is already in tsconfig.json
```
/* Modules */
    "module": "commonjs",  
```
contradicts each other

I dont know maybe its my machine

but i think the adding esm to the project is unnecesary

**Comment by Nathan-Somto** [comment]
Thanks for pointing this out,
The flags
```--files and --esm```
Are important for tsnode to execute all files that end with .ts and also handle esm imports and exports.

  ``` 
"ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  }, 

```
This was done deliberately and typescript ignores this config it is for tsnode to resolve esm modules

```
/* Modules */
    "module": "commonjs",  
```
Does not really contradict just allows for the compiled files to have commonjs syntax which makes  are project backwards compatitable (this is a ts default.)

Some troubleshooting
- check if you have ts and ts-node installed.
- and run the server using the specified scripts

**Comment by Nathan-Somto** [comment]
Might be a machine issue,
I added those flags because it did not work without them

**Comment by Temiloluwa-Ogundiran** [comment]
it was my version of node, I downgraded using nvm and it worked
